// Protocol buffer definition for Geofence Fence Items
// This file defines the binary format for individual geofence restrictions

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: fence.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FenceType defines the category of the geofence restriction
type FenceType int32

const (
	FenceType_FENCE_TYPE_UNKNOWN FenceType = 0
	// Temporary restriction for events, emergency response, etc.
	FenceType_FENCE_TYPE_TEMP_RESTRICTION FenceType = 1
	// Permanent no-fly zone (airports, military bases, etc.)
	FenceType_FENCE_TYPE_PERMANENT_NO_FLY FenceType = 2
	// Altitude restriction (max height limit)
	FenceType_FENCE_TYPE_ALTITUDE_LIMIT FenceType = 3
	// Minimum altitude requirement (e.g., stay above certain height)
	FenceType_FENCE_TYPE_ALTITUDE_MINIMUM FenceType = 4
	// Speed restriction zone
	FenceType_FENCE_TYPE_SPEED_LIMIT FenceType = 5
)

// Enum value maps for FenceType.
var (
	FenceType_name = map[int32]string{
		0: "FENCE_TYPE_UNKNOWN",
		1: "FENCE_TYPE_TEMP_RESTRICTION",
		2: "FENCE_TYPE_PERMANENT_NO_FLY",
		3: "FENCE_TYPE_ALTITUDE_LIMIT",
		4: "FENCE_TYPE_ALTITUDE_MINIMUM",
		5: "FENCE_TYPE_SPEED_LIMIT",
	}
	FenceType_value = map[string]int32{
		"FENCE_TYPE_UNKNOWN":          0,
		"FENCE_TYPE_TEMP_RESTRICTION": 1,
		"FENCE_TYPE_PERMANENT_NO_FLY": 2,
		"FENCE_TYPE_ALTITUDE_LIMIT":   3,
		"FENCE_TYPE_ALTITUDE_MINIMUM": 4,
		"FENCE_TYPE_SPEED_LIMIT":      5,
	}
)

func (x FenceType) Enum() *FenceType {
	p := new(FenceType)
	*p = x
	return p
}

func (x FenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_fence_proto_enumTypes[0].Descriptor()
}

func (FenceType) Type() protoreflect.EnumType {
	return &file_fence_proto_enumTypes[0]
}

func (x FenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FenceType.Descriptor instead.
func (FenceType) EnumDescriptor() ([]byte, []int) {
	return file_fence_proto_rawDescGZIP(), []int{0}
}

// Geometry defines the spatial shape of the fence
type Geometry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Shape:
	//
	//	*Geometry_Polygon
	//	*Geometry_Circle
	//	*Geometry_Bbox
	Shape         isGeometry_Shape `protobuf_oneof:"shape"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geometry) Reset() {
	*x = Geometry{}
	mi := &file_fence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geometry) ProtoMessage() {}

func (x *Geometry) ProtoReflect() protoreflect.Message {
	mi := &file_fence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geometry.ProtoReflect.Descriptor instead.
func (*Geometry) Descriptor() ([]byte, []int) {
	return file_fence_proto_rawDescGZIP(), []int{0}
}

func (x *Geometry) GetShape() isGeometry_Shape {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *Geometry) GetPolygon() *Polygon {
	if x != nil {
		if x, ok := x.Shape.(*Geometry_Polygon); ok {
			return x.Polygon
		}
	}
	return nil
}

func (x *Geometry) GetCircle() *Circle {
	if x != nil {
		if x, ok := x.Shape.(*Geometry_Circle); ok {
			return x.Circle
		}
	}
	return nil
}

func (x *Geometry) GetBbox() *BoundingBox {
	if x != nil {
		if x, ok := x.Shape.(*Geometry_Bbox); ok {
			return x.Bbox
		}
	}
	return nil
}

type isGeometry_Shape interface {
	isGeometry_Shape()
}

type Geometry_Polygon struct {
	// Polygon defined by ordered list of points
	Polygon *Polygon `protobuf:"bytes,1,opt,name=polygon,proto3,oneof"`
}

type Geometry_Circle struct {
	// Circle defined by center point and radius in meters
	Circle *Circle `protobuf:"bytes,2,opt,name=circle,proto3,oneof"`
}

type Geometry_Bbox struct {
	// Bounding box (min_lat, min_lon, max_lat, max_lon)
	Bbox *BoundingBox `protobuf:"bytes,3,opt,name=bbox,proto3,oneof"`
}

func (*Geometry_Polygon) isGeometry_Shape() {}

func (*Geometry_Circle) isGeometry_Shape() {}

func (*Geometry_Bbox) isGeometry_Shape() {}

// Polygon represents a closed shape defined by vertices
type Polygon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Coordinates in [latitude, longitude] pairs
	// Lat/Lon in degrees (WGS84)
	Coordinates   []*Point `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	mi := &file_fence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_fence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_fence_proto_rawDescGZIP(), []int{1}
}

func (x *Polygon) GetCoordinates() []*Point {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

// Circle represents a circular geofence
type Circle struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Center *Point                 `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	// Radius in meters
	RadiusMeters  float64 `protobuf:"fixed64,2,opt,name=radius_meters,json=radiusMeters,proto3" json:"radius_meters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Circle) Reset() {
	*x = Circle{}
	mi := &file_fence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Circle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Circle) ProtoMessage() {}

func (x *Circle) ProtoReflect() protoreflect.Message {
	mi := &file_fence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Circle.ProtoReflect.Descriptor instead.
func (*Circle) Descriptor() ([]byte, []int) {
	return file_fence_proto_rawDescGZIP(), []int{2}
}

func (x *Circle) GetCenter() *Point {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *Circle) GetRadiusMeters() float64 {
	if x != nil {
		return x.RadiusMeters
	}
	return 0
}

// Point represents a single coordinate
type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`   // Degrees, -90 to 90
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"` // Degrees, -180 to 180
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_fence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_fence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_fence_proto_rawDescGZIP(), []int{3}
}

func (x *Point) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// BoundingBox represents a rectangular area
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLat        float64                `protobuf:"fixed64,1,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MinLon        float64                `protobuf:"fixed64,2,opt,name=min_lon,json=minLon,proto3" json:"min_lon,omitempty"`
	MaxLat        float64                `protobuf:"fixed64,3,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	MaxLon        float64                `protobuf:"fixed64,4,opt,name=max_lon,json=maxLon,proto3" json:"max_lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_fence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_fence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_fence_proto_rawDescGZIP(), []int{4}
}

func (x *BoundingBox) GetMinLat() float64 {
	if x != nil {
		return x.MinLat
	}
	return 0
}

func (x *BoundingBox) GetMinLon() float64 {
	if x != nil {
		return x.MinLon
	}
	return 0
}

func (x *BoundingBox) GetMaxLat() float64 {
	if x != nil {
		return x.MaxLat
	}
	return 0
}

func (x *BoundingBox) GetMaxLon() float64 {
	if x != nil {
		return x.MaxLon
	}
	return 0
}

// FenceItem represents a single geofence restriction
// This is the core data unit that gets signed and distributed
type FenceItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this fence
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type of restriction
	Type FenceType `protobuf:"varint,2,opt,name=type,proto3,enum=gul.protocol.v1.FenceType" json:"type,omitempty"`
	// Spatial definition
	Geometry *Geometry `protobuf:"bytes,3,opt,name=geometry,proto3" json:"geometry,omitempty"`
	// Time validity window (Unix timestamps)
	// Use protobuf well-known types for better compatibility
	StartTs int64 `protobuf:"varint,4,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"` // Unix timestamp in seconds
	EndTs   int64 `protobuf:"varint,5,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`       // Unix timestamp in seconds, 0 means no expiry
	// Priority level (higher = more important)
	// When multiple fences overlap, the highest priority wins
	Priority uint32 `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	// For altitude restrictions: max height in meters (0 = no limit)
	MaxAltitudeMeters uint32 `protobuf:"varint,7,opt,name=max_altitude_meters,json=maxAltitudeMeters,proto3" json:"max_altitude_meters,omitempty"`
	// For speed restrictions: max speed in m/s (0 = no limit)
	MaxSpeedMps uint32 `protobuf:"varint,8,opt,name=max_speed_mps,json=maxSpeedMps,proto3" json:"max_speed_mps,omitempty"`
	// Human-readable description
	Name        string `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	// Ed25519 signature of all above fields
	// The signature is computed over the serialized protobuf message
	// without this signature field included
	Signature []byte `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	// Public key ID that can verify this signature
	KeyId         string `protobuf:"bytes,12,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FenceItem) Reset() {
	*x = FenceItem{}
	mi := &file_fence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FenceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceItem) ProtoMessage() {}

func (x *FenceItem) ProtoReflect() protoreflect.Message {
	mi := &file_fence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceItem.ProtoReflect.Descriptor instead.
func (*FenceItem) Descriptor() ([]byte, []int) {
	return file_fence_proto_rawDescGZIP(), []int{5}
}

func (x *FenceItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FenceItem) GetType() FenceType {
	if x != nil {
		return x.Type
	}
	return FenceType_FENCE_TYPE_UNKNOWN
}

func (x *FenceItem) GetGeometry() *Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *FenceItem) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *FenceItem) GetEndTs() int64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *FenceItem) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *FenceItem) GetMaxAltitudeMeters() uint32 {
	if x != nil {
		return x.MaxAltitudeMeters
	}
	return 0
}

func (x *FenceItem) GetMaxSpeedMps() uint32 {
	if x != nil {
		return x.MaxSpeedMps
	}
	return 0
}

func (x *FenceItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FenceItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FenceItem) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *FenceItem) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// FenceCollection represents a batch of fence items
// Used for snapshot files and delta updates
type FenceCollection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*FenceItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Collection metadata
	CreatedTs     int64  `protobuf:"varint,2,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FenceCollection) Reset() {
	*x = FenceCollection{}
	mi := &file_fence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FenceCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceCollection) ProtoMessage() {}

func (x *FenceCollection) ProtoReflect() protoreflect.Message {
	mi := &file_fence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceCollection.ProtoReflect.Descriptor instead.
func (*FenceCollection) Descriptor() ([]byte, []int) {
	return file_fence_proto_rawDescGZIP(), []int{6}
}

func (x *FenceCollection) GetItems() []*FenceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FenceCollection) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *FenceCollection) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// FenceDelta represents changes between two versions
type FenceDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fences to add
	Added []*FenceItem `protobuf:"bytes,1,rep,name=added,proto3" json:"added,omitempty"`
	// IDs of fences to remove
	RemovedIds []string `protobuf:"bytes,2,rep,name=removed_ids,json=removedIds,proto3" json:"removed_ids,omitempty"`
	// Fences to update (new version replaces old)
	Updated       []*FenceItem `protobuf:"bytes,3,rep,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FenceDelta) Reset() {
	*x = FenceDelta{}
	mi := &file_fence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FenceDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceDelta) ProtoMessage() {}

func (x *FenceDelta) ProtoReflect() protoreflect.Message {
	mi := &file_fence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceDelta.ProtoReflect.Descriptor instead.
func (*FenceDelta) Descriptor() ([]byte, []int) {
	return file_fence_proto_rawDescGZIP(), []int{7}
}

func (x *FenceDelta) GetAdded() []*FenceItem {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *FenceDelta) GetRemovedIds() []string {
	if x != nil {
		return x.RemovedIds
	}
	return nil
}

func (x *FenceDelta) GetUpdated() []*FenceItem {
	if x != nil {
		return x.Updated
	}
	return nil
}

var File_fence_proto protoreflect.FileDescriptor

const file_fence_proto_rawDesc = "" +
	"\n" +
	"\vfence.proto\x12\x0fgul.protocol.v1\"\xb0\x01\n" +
	"\bGeometry\x124\n" +
	"\apolygon\x18\x01 \x01(\v2\x18.gul.protocol.v1.PolygonH\x00R\apolygon\x121\n" +
	"\x06circle\x18\x02 \x01(\v2\x17.gul.protocol.v1.CircleH\x00R\x06circle\x122\n" +
	"\x04bbox\x18\x03 \x01(\v2\x1c.gul.protocol.v1.BoundingBoxH\x00R\x04bboxB\a\n" +
	"\x05shape\"C\n" +
	"\aPolygon\x128\n" +
	"\vcoordinates\x18\x01 \x03(\v2\x16.gul.protocol.v1.PointR\vcoordinates\"]\n" +
	"\x06Circle\x12.\n" +
	"\x06center\x18\x01 \x01(\v2\x16.gul.protocol.v1.PointR\x06center\x12#\n" +
	"\rradius_meters\x18\x02 \x01(\x01R\fradiusMeters\"A\n" +
	"\x05Point\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"q\n" +
	"\vBoundingBox\x12\x17\n" +
	"\amin_lat\x18\x01 \x01(\x01R\x06minLat\x12\x17\n" +
	"\amin_lon\x18\x02 \x01(\x01R\x06minLon\x12\x17\n" +
	"\amax_lat\x18\x03 \x01(\x01R\x06maxLat\x12\x17\n" +
	"\amax_lon\x18\x04 \x01(\x01R\x06maxLon\"\x8f\x03\n" +
	"\tFenceItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.gul.protocol.v1.FenceTypeR\x04type\x125\n" +
	"\bgeometry\x18\x03 \x01(\v2\x19.gul.protocol.v1.GeometryR\bgeometry\x12\x19\n" +
	"\bstart_ts\x18\x04 \x01(\x03R\astartTs\x12\x15\n" +
	"\x06end_ts\x18\x05 \x01(\x03R\x05endTs\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\rR\bpriority\x12.\n" +
	"\x13max_altitude_meters\x18\a \x01(\rR\x11maxAltitudeMeters\x12\"\n" +
	"\rmax_speed_mps\x18\b \x01(\rR\vmaxSpeedMps\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x1c\n" +
	"\tsignature\x18\v \x01(\fR\tsignature\x12\x15\n" +
	"\x06key_id\x18\f \x01(\tR\x05keyId\"|\n" +
	"\x0fFenceCollection\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.gul.protocol.v1.FenceItemR\x05items\x12\x1d\n" +
	"\n" +
	"created_ts\x18\x02 \x01(\x03R\tcreatedTs\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x95\x01\n" +
	"\n" +
	"FenceDelta\x120\n" +
	"\x05added\x18\x01 \x03(\v2\x1a.gul.protocol.v1.FenceItemR\x05added\x12\x1f\n" +
	"\vremoved_ids\x18\x02 \x03(\tR\n" +
	"removedIds\x124\n" +
	"\aupdated\x18\x03 \x03(\v2\x1a.gul.protocol.v1.FenceItemR\aupdated*\xc1\x01\n" +
	"\tFenceType\x12\x16\n" +
	"\x12FENCE_TYPE_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bFENCE_TYPE_TEMP_RESTRICTION\x10\x01\x12\x1f\n" +
	"\x1bFENCE_TYPE_PERMANENT_NO_FLY\x10\x02\x12\x1d\n" +
	"\x19FENCE_TYPE_ALTITUDE_LIMIT\x10\x03\x12\x1f\n" +
	"\x1bFENCE_TYPE_ALTITUDE_MINIMUM\x10\x04\x12\x1a\n" +
	"\x16FENCE_TYPE_SPEED_LIMIT\x10\x05B?Z=github.com/iannil/geofence-updater-lite/pkg/protocol/protobufb\x06proto3"

var (
	file_fence_proto_rawDescOnce sync.Once
	file_fence_proto_rawDescData []byte
)

func file_fence_proto_rawDescGZIP() []byte {
	file_fence_proto_rawDescOnce.Do(func() {
		file_fence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fence_proto_rawDesc), len(file_fence_proto_rawDesc)))
	})
	return file_fence_proto_rawDescData
}

var file_fence_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fence_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_fence_proto_goTypes = []any{
	(FenceType)(0),          // 0: gul.protocol.v1.FenceType
	(*Geometry)(nil),        // 1: gul.protocol.v1.Geometry
	(*Polygon)(nil),         // 2: gul.protocol.v1.Polygon
	(*Circle)(nil),          // 3: gul.protocol.v1.Circle
	(*Point)(nil),           // 4: gul.protocol.v1.Point
	(*BoundingBox)(nil),     // 5: gul.protocol.v1.BoundingBox
	(*FenceItem)(nil),       // 6: gul.protocol.v1.FenceItem
	(*FenceCollection)(nil), // 7: gul.protocol.v1.FenceCollection
	(*FenceDelta)(nil),      // 8: gul.protocol.v1.FenceDelta
}
var file_fence_proto_depIdxs = []int32{
	2,  // 0: gul.protocol.v1.Geometry.polygon:type_name -> gul.protocol.v1.Polygon
	3,  // 1: gul.protocol.v1.Geometry.circle:type_name -> gul.protocol.v1.Circle
	5,  // 2: gul.protocol.v1.Geometry.bbox:type_name -> gul.protocol.v1.BoundingBox
	4,  // 3: gul.protocol.v1.Polygon.coordinates:type_name -> gul.protocol.v1.Point
	4,  // 4: gul.protocol.v1.Circle.center:type_name -> gul.protocol.v1.Point
	0,  // 5: gul.protocol.v1.FenceItem.type:type_name -> gul.protocol.v1.FenceType
	1,  // 6: gul.protocol.v1.FenceItem.geometry:type_name -> gul.protocol.v1.Geometry
	6,  // 7: gul.protocol.v1.FenceCollection.items:type_name -> gul.protocol.v1.FenceItem
	6,  // 8: gul.protocol.v1.FenceDelta.added:type_name -> gul.protocol.v1.FenceItem
	6,  // 9: gul.protocol.v1.FenceDelta.updated:type_name -> gul.protocol.v1.FenceItem
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_fence_proto_init() }
func file_fence_proto_init() {
	if File_fence_proto != nil {
		return
	}
	file_fence_proto_msgTypes[0].OneofWrappers = []any{
		(*Geometry_Polygon)(nil),
		(*Geometry_Circle)(nil),
		(*Geometry_Bbox)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fence_proto_rawDesc), len(file_fence_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fence_proto_goTypes,
		DependencyIndexes: file_fence_proto_depIdxs,
		EnumInfos:         file_fence_proto_enumTypes,
		MessageInfos:      file_fence_proto_msgTypes,
	}.Build()
	File_fence_proto = out.File
	file_fence_proto_goTypes = nil
	file_fence_proto_depIdxs = nil
}
