// Protocol buffer definition for Geofence Manifest
// This file defines the binary format for the version manifest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: manifest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Manifest represents the current state of the geofence database
// This is the small file that clients poll frequently to check for updates
type Manifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing version number
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Unix timestamp when this manifest was created
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Merkle tree root hash for integrity verification
	RootHash []byte `protobuf:"bytes,3,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	// URL path for delta update from previous version
	// Relative to CDN base URL, e.g., "/patches/v1023_to_v1024.bin"
	DeltaUrl string `protobuf:"bytes,4,opt,name=delta_url,json=deltaUrl,proto3" json:"delta_url,omitempty"`
	// URL path for full snapshot download
	// For new devices or when client is too far behind
	SnapshotUrl string `protobuf:"bytes,5,opt,name=snapshot_url,json=snapshotUrl,proto3" json:"snapshot_url,omitempty"`
	// Size of delta file in bytes (for clients to estimate download)
	DeltaSize uint64 `protobuf:"varint,6,opt,name=delta_size,json=deltaSize,proto3" json:"delta_size,omitempty"`
	// Size of snapshot file in bytes
	SnapshotSize uint64 `protobuf:"varint,7,opt,name=snapshot_size,json=snapshotSize,proto3" json:"snapshot_size,omitempty"`
	// Hash of delta file (SHA-256) for download verification
	DeltaHash []byte `protobuf:"bytes,8,opt,name=delta_hash,json=deltaHash,proto3" json:"delta_hash,omitempty"`
	// Hash of snapshot file (SHA-256) for download verification
	SnapshotHash []byte `protobuf:"bytes,9,opt,name=snapshot_hash,json=snapshotHash,proto3" json:"snapshot_hash,omitempty"`
	// Minimum supported client version
	// Clients below this version must update before fetching new data
	MinClientVersion uint32 `protobuf:"varint,10,opt,name=min_client_version,json=minClientVersion,proto3" json:"min_client_version,omitempty"`
	// Human-readable message about this update
	Message string `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	// Signature of the manifest (Ed25519)
	// Computed over all fields except this signature field
	Signature []byte `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	// Public key ID that can verify this signature
	KeyId         string `protobuf:"bytes,13,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Manifest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Manifest) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *Manifest) GetDeltaUrl() string {
	if x != nil {
		return x.DeltaUrl
	}
	return ""
}

func (x *Manifest) GetSnapshotUrl() string {
	if x != nil {
		return x.SnapshotUrl
	}
	return ""
}

func (x *Manifest) GetDeltaSize() uint64 {
	if x != nil {
		return x.DeltaSize
	}
	return 0
}

func (x *Manifest) GetSnapshotSize() uint64 {
	if x != nil {
		return x.SnapshotSize
	}
	return 0
}

func (x *Manifest) GetDeltaHash() []byte {
	if x != nil {
		return x.DeltaHash
	}
	return nil
}

func (x *Manifest) GetSnapshotHash() []byte {
	if x != nil {
		return x.SnapshotHash
	}
	return nil
}

func (x *Manifest) GetMinClientVersion() uint32 {
	if x != nil {
		return x.MinClientVersion
	}
	return 0
}

func (x *Manifest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Manifest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Manifest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// ManifestRequest is used for querying specific manifest versions
type ManifestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request specific version (0 = latest)
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Current client version (for server-side compatibility check)
	ClientVersion uint32 `protobuf:"varint,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *ManifestRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ManifestRequest) GetClientVersion() uint32 {
	if x != nil {
		return x.ClientVersion
	}
	return 0
}

// ManifestResponse wraps a manifest with additional metadata
type ManifestResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Manifest *Manifest              `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	// CDN base URL for resolving relative paths
	CdnBaseUrl string `protobuf:"bytes,2,opt,name=cdn_base_url,json=cdnBaseUrl,proto3" json:"cdn_base_url,omitempty"`
	// Indicates if a delta is available from the specified version
	DeltaAvailable bool `protobuf:"varint,3,opt,name=delta_available,json=deltaAvailable,proto3" json:"delta_available,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ManifestResponse) Reset() {
	*x = ManifestResponse{}
	mi := &file_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestResponse) ProtoMessage() {}

func (x *ManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestResponse.ProtoReflect.Descriptor instead.
func (*ManifestResponse) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *ManifestResponse) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *ManifestResponse) GetCdnBaseUrl() string {
	if x != nil {
		return x.CdnBaseUrl
	}
	return ""
}

func (x *ManifestResponse) GetDeltaAvailable() bool {
	if x != nil {
		return x.DeltaAvailable
	}
	return false
}

var File_manifest_proto protoreflect.FileDescriptor

const file_manifest_proto_rawDesc = "" +
	"\n" +
	"\x0emanifest.proto\x12\x0fgul.protocol.v1\"\xa4\x03\n" +
	"\bManifest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\troot_hash\x18\x03 \x01(\fR\brootHash\x12\x1b\n" +
	"\tdelta_url\x18\x04 \x01(\tR\bdeltaUrl\x12!\n" +
	"\fsnapshot_url\x18\x05 \x01(\tR\vsnapshotUrl\x12\x1d\n" +
	"\n" +
	"delta_size\x18\x06 \x01(\x04R\tdeltaSize\x12#\n" +
	"\rsnapshot_size\x18\a \x01(\x04R\fsnapshotSize\x12\x1d\n" +
	"\n" +
	"delta_hash\x18\b \x01(\fR\tdeltaHash\x12#\n" +
	"\rsnapshot_hash\x18\t \x01(\fR\fsnapshotHash\x12,\n" +
	"\x12min_client_version\x18\n" +
	" \x01(\rR\x10minClientVersion\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\x12\x1c\n" +
	"\tsignature\x18\f \x01(\fR\tsignature\x12\x15\n" +
	"\x06key_id\x18\r \x01(\tR\x05keyId\"R\n" +
	"\x0fManifestRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\rR\rclientVersion\"\x94\x01\n" +
	"\x10ManifestResponse\x125\n" +
	"\bmanifest\x18\x01 \x01(\v2\x19.gul.protocol.v1.ManifestR\bmanifest\x12 \n" +
	"\fcdn_base_url\x18\x02 \x01(\tR\n" +
	"cdnBaseUrl\x12'\n" +
	"\x0fdelta_available\x18\x03 \x01(\bR\x0edeltaAvailableB?Z=github.com/iannil/geofence-updater-lite/pkg/protocol/protobufb\x06proto3"

var (
	file_manifest_proto_rawDescOnce sync.Once
	file_manifest_proto_rawDescData []byte
)

func file_manifest_proto_rawDescGZIP() []byte {
	file_manifest_proto_rawDescOnce.Do(func() {
		file_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manifest_proto_rawDesc), len(file_manifest_proto_rawDesc)))
	})
	return file_manifest_proto_rawDescData
}

var file_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_manifest_proto_goTypes = []any{
	(*Manifest)(nil),         // 0: gul.protocol.v1.Manifest
	(*ManifestRequest)(nil),  // 1: gul.protocol.v1.ManifestRequest
	(*ManifestResponse)(nil), // 2: gul.protocol.v1.ManifestResponse
}
var file_manifest_proto_depIdxs = []int32{
	0, // 0: gul.protocol.v1.ManifestResponse.manifest:type_name -> gul.protocol.v1.Manifest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_manifest_proto_init() }
func file_manifest_proto_init() {
	if File_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manifest_proto_rawDesc), len(file_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manifest_proto_goTypes,
		DependencyIndexes: file_manifest_proto_depIdxs,
		MessageInfos:      file_manifest_proto_msgTypes,
	}.Build()
	File_manifest_proto = out.File
	file_manifest_proto_goTypes = nil
	file_manifest_proto_depIdxs = nil
}
